on:
  - push
  - pull_request

jobs:
  lint-experimental-modules:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build-experimental-modules:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      match-path: "test/**/*.sol"
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

  simulate-experimental-modules:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-simulate.yaml@main"
    with:
      match-path: "test/**/*.sol"
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
